'use strict';
const db = window.db; const $ = s=>document.querySelector(s); const $$=s=>[...document.querySelectorAll(s)];
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const isAdmin=user=>user?.app_metadata?.role==='admin';
function mostrarPanel(user){ $('#login').classList.add('oculto'); $('#panel').classList.remove('oculto'); $('#admin-identidad').textContent=user.email; cargarTodo(); }
async function autenticar(e){e.preventDefault();$('#login-estado').textContent='Verificando…';const{data,error}=await db.auth.signInWithPassword({email:$('#admin-email').value.trim(),password:$('#admin-password').value});if(error||!isAdmin(data.user)){await db.auth.signOut();$('#login-estado').textContent=error?.message||'Esta cuenta no tiene rol de administrador.';return;}mostrarPanel(data.user);}
async function sesion(){const{data:{user}}=await db.auth.getUser();if(user&&isAdmin(user))mostrarPanel(user);}
async function configs(){const{data,error}=await db.from('configuracion').select('*');if(error)throw error;const c=Object.fromEntries(data.map(x=>[x.clave,x.valore??x.valor]));$('#cfg-total').value=c.total_cartones||300;$('#cfg-precio').value=c.precio_carton||0;$('#cfg-ventas').checked=c.ventas_abierta===true||c.ventas_abierta==='true';$('#cfg-modo').value=c.modo_cartones||'libre';$('#cfg-fijos').value=c.cartones_obligatorios||1;$('#cfg-whatsapp').value=c.link_whatsapp||'';$('#cfg-youtube').value=c.youtube_live||'';}
async function guardarConfig(e){e.preventDefault();const rows=[['total_cartones',$('#cfg-total').value,null],['precio_carton',$('#cfg-precio').value,null],['ventas_abierta',null,$('#cfg-ventas').checked],['modo_cartones',$('#cfg-modo').value,null],['cartones_obligatorios',$('#cfg-fijos').value,null],['link_whatsapp',$('#cfg-whatsapp').value,null],['youtube_live',$('#cfg-youtube').value,null]].map(([clave,valore,valor])=>({clave,valore,valor}));const{error}=await db.from('configuracion').upsert(rows,{onConflict:'clave'});alert(error?error.message:'Configuración guardada.');}
async function inscripciones(){const{data,error}=await db.from('inscripciones').select('*').order('created_at',{ascending:false});if(error)throw error;$('#stat-clientes').textContent=data.length;$('#stat-cartones').textContent=data.reduce((n,x)=>n+(x.cartones?.length||0),0);$('#stat-monto').textContent=`${data.filter(x=>x.estado==='aprobado').reduce((n,x)=>n+Number(x.monto_bs||0),0).toFixed(2)} Bs`;const tbody=$('#tabla-inscripciones tbody');tbody.innerHTML='';for(const x of data){let url='';if(x.comprobante){const r=await db.storage.from('comprobantes').createSignedUrl(x.comprobante,900);url=r.data?.signedUrl||'';}const tr=document.createElement('tr');tr.innerHTML=`<td><b>${esc(x.nombre)}</b><br>${esc(x.cedula)}</td><td>${esc(x.telefono)}<br>Ref: ${esc(x.referencia4dig)}</td><td>${esc((x.cartones||[]).join(', '))}</td><td>${Number(x.monto_bs||0).toFixed(2)} Bs<br>${url?`<a href="${url}" target="_blank" rel="noopener">Ver comprobante</a>`:'Sin archivo'}</td><td>${esc(x.estado)}</td><td><button data-estado="aprobado">Aprobar</button><button data-estado="rechazado" class="btn-secondary">Rechazar</button><button data-borrar class="btn-danger">Eliminar</button></td>`;tr.querySelectorAll('[data-estado]').forEach(b=>b.addEventListener('click',()=>estado(x.id,b.dataset.estado)));tr.querySelector('[data-borrar]').addEventListener('click',()=>borrar(x));tbody.appendChild(tr);}}
async function estado(id,estado){const{error}=await db.from('inscripciones').update({estado}).eq('id',id);if(error)alert(error.message);else inscripciones();}
async function borrar(x){if(!confirm(`¿Eliminar la inscripción de ${x.nombre}?`))return;const{error}=await db.from('inscripciones').delete().eq('id',x.id);if(error)return alert(error.message);if(x.comprobante)await db.storage.from('comprobantes').remove([x.comprobante]);await db.from('cartones').delete().in('numero',(x.cartones||[]).map(Number));inscripciones();}
async function ganador(e){e.preventDefault();const row={nombre:$('#g-nombre').value.trim(),cedula:$('#g-cedula').value.trim(),cartones:$('#g-cartones').value.trim(),premio:$('#g-premio').value.trim(),telefono:$('#g-telefono').value.trim(),fecha:$('#g-fecha').value};const{error}=await db.from('ganadores').insert(row);if(error)alert(error.message);else{e.target.reset();ganadores();}}
async function ganadores(){const{data,error}=await db.from('ganadores').select('*').order('fecha',{ascending:false});$('#ganadores-admin-lista').innerHTML=error?esc(error.message):(data||[]).map(x=>`<article class="panel-section"><b>${esc(x.nombre)}</b> · ${esc(x.premio)} · ${esc(x.fecha)}</article>`).join('');}
async function cargarTodo(){try{await Promise.all([configs(),inscripciones(),ganadores()]);}catch(e){alert(e.message);}}
document.addEventListener('DOMContentLoaded',()=>{$('#login-form').addEventListener('submit',autenticar);$('#logout').addEventListener('click',async()=>{await db.auth.signOut();location.reload();});$('#recargar').addEventListener('click',cargarTodo);$('#config-form').addEventListener('submit',guardarConfig);$('#ganador-form').addEventListener('submit',ganador);$$('[data-tab]').forEach(b=>b.addEventListener('click',()=>{$$('[data-tab]').forEach(x=>x.classList.remove('active'));$$('.tab-content').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.getElementById(b.dataset.tab).classList.add('active');}));sesion();});
